---
sshd_port: 2222

ansible_ssh_user: ansible
ansible_ssh_port: "{{ sshd_port }}"
ansible_become: yes

sshd:
  Port: "{{ sshd_port }}"
  PermitRootLogin: no
  PasswordAuthentication: no


fail2ban_services:
  - name: sshd
    port: "{{ sshd_port }}" 
    maxretry: 5
    bantime: -1