---
sshd_port: 2222

ansible_ssh_user: ansible
ansible_ssh_port: "{{ sshd_port }}"

sshd:
  Port: "{{ sshd_port }}"
  PermitRootLogin: no
  PasswordAuthentication: no

fail2ban_services:
  - name: sshd
    port: "{{ sshd_port }}"
    maxretry: 5
    bantime: -1

node_exporter_version: 1.3.1
node_exporter_web_listen_address: 127.0.0.1:9100
