---
  - name: bootstrap
    hosts: all
    roles:
      - bootstrap
      - willshersystems.sshd
    vars:
      ansible_ssh_user: root
      ansible_ssh_port: 22
    tags: never, bootstrap

  - hosts: all
    roles:
      - oefenweb.fail2ban
    tags: common, bootstrap

  - hosts: grafana
    become: yes
    roles:
      - role: cloudalchemy.grafana
      - role: geerlingguy.certbot
        tags: certbot
    tags: grafana