---
  - name: bootstrap
    hosts: ansible 
    roles:
      - bootstrap
      - willshersystems.sshd
    vars:
      ansible_ssh_user: root
      ansible_ssh_port: 22
    tags: never, bootstrap

  - hosts: ansible
    roles:
      - oefenweb.fail2ban
      - cloudalchemy.node_exporter
    tags: common, bootstrap
  
  - hosts: grafana1.hegedus.wtf,vectordev1.hegedus.wtf
    become: yes
    roles:
      - role: geerlingguy.certbot
        tags: certbot
    post_tasks:
      - name: change ownership of letsencrypt dirs
        file:
          path: /etc/letsencrypt
          owner: "{{ certbot_user }}"
          recurse: yes
        when: snapd_install is changed
  
  - hosts: grafana1.hegedus.wtf
    become: yes
    roles:
      - role: cloudalchemy.grafana
    tags: grafana