---
  - hosts: all
    roles:
      - oefenweb.fail2ban
    tags: common

  - hosts: grafana
    become: yes
    roles:
      - role: cloudalchemy.grafana
      - role: geerlingguy.certbot
        tags: certbot