---
plugin: community.general.linode
access_token: "{{ lookup('ini', 'token section=wbh1 file=~/.config/linode-cli' ) }}"
groups:
  blog: "label == 'wbhegedus.me'"
  salt: "'salt' in label"
compose:
  # By default, Ansible tries to connect to the label of the instance.
  # Since that might not be a valid name to connect to, you can
  # replace it with the first IPv4 address of the linode as follows:
  ansible_ssh_host: ipv4[0]
keyed_groups:
  - key: tags
    separator: ''
  - key: region
    prefix: region
